# Generated by Django 3.1.3 on 2020-12-07 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100, verbose_name='название фильма')),
                ('movie_title_eng', models.CharField(max_length=100, verbose_name='название фильма англ')),
                ('genre', models.CharField(max_length=100, verbose_name='жанр')),
                ('duration', models.CharField(max_length=50, verbose_name='продолжительность')),
                ('premiere', models.DateField(default=django.utils.timezone.now)),
                ('country', models.CharField(max_length=100, verbose_name='страна производства')),
                ('director', models.CharField(max_length=100, verbose_name='режиссер')),
                ('cast', models.CharField(max_length=250, verbose_name='актеры')),
                ('plot', models.TextField(verbose_name='краткое описание')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
