# Generated by Django 3.1.3 on 2020-12-07 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('cinema', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='premiere',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='премьера'),
        ),
    ]
