# Generated by Django 3.1.3 on 2020-12-15 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_auto_20201215_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='end_of_distribution',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='конечная дата проката'),
        ),
    ]
