# Generated by Django 3.1.3 on 2020-12-17 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_auto_20201216_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='начало сеанса')),
                ('end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='конец сеанса')),
                ('hall', models.IntegerField(verbose_name='номер зала')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seance', to='cinema.movie', verbose_name='фильм')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
    ]
