# Generated by Django 3.1.3 on 2020-12-19 12:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_auto_20201217_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 19, 12, 57, 48, 307915, tzinfo=utc), verbose_name='конец сеанса'),
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(verbose_name='ряд')),
                ('seat', models.IntegerField(verbose_name='место')),
                ('type', models.BinaryField(default=False, verbose_name='свободно/занято')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seance', verbose_name='сеанс')),
            ],
        ),
    ]
