# Generated by Django 3.1.3 on 2020-12-19 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_auto_20201219_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 19, 13, 8, 26, 348781, tzinfo=utc), verbose_name='конец сеанса'),
        ),
        migrations.AlterField(
            model_name='seats',
            name='type',
            field=models.BinaryField(verbose_name='свободно/занято'),
        ),
    ]
