# Generated by Django 3.1.3 on 2020-12-19 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_auto_20201219_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 19, 13, 9, 18, 115813, tzinfo=utc), verbose_name='конец сеанса'),
        ),
    ]
