# Generated by Django 3.1.3 on 2020-12-19 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('cinema', '0014_auto_20201219_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 19, 13, 11, 47, 88648, tzinfo=utc),
                                       verbose_name='конец сеанса'),
        ),
        migrations.DeleteModel(
            name='Seats',
        ),
    ]
