# Generated by Django 3.1.3 on 2020-12-29 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_auto_20201229_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 11, 42, 58, 453089, tzinfo=utc), verbose_name='конец сеанса'),
        ),
    ]
