# Generated by Django 3.1.3 on 2021-01-23 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0017_auto_20201229_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.AlterField(
            model_name='seance',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 10, 9, 54, 689646, tzinfo=utc), verbose_name='конец сеанса'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(verbose_name='ряд')),
                ('seat', models.IntegerField(verbose_name='место')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seance', verbose_name='сеанс')),
            ],
        ),
    ]
