# Generated by Django 3.1.3 on 2021-01-23 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0018_auto_20210123_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 10, 51, 51, 270156, tzinfo=utc), verbose_name='конец сеанса'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.CharField(max_length=3, verbose_name='ряд'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.CharField(max_length=3, verbose_name='место'),
        ),
    ]
