# Generated by Django 3.1.3 on 2021-01-27 08:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0020_auto_20210126_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 8, 26, 26, 541567, tzinfo=utc), verbose_name='конец сеанса'),
        ),
    ]
