# Generated by Django 3.1.3 on 2021-01-27 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0021_auto_20210127_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='конец сеанса'),
        ),
    ]
